[package]
name = "Deep-Learning-from-scratch"
version = "0.1.0"
edition = "2024"

[dependencies]
mnist = "0.6.0"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
ndarray-stats = "0.6.0"
plotters = "0.3.7"
rand = "0.9.2"
rand_distr = "0.5.1"
